# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes: [
  ]
derivedTypes: [
  ]
descriptionHTML: ' '
name: weblogic.j2ee.descriptor.wl.ApplicationEntityCacheBean
properties:
- defaultValue:
    value:
      value: 100
  descriptionHTML: ' '
  name: MaxQueriesInCache
  restartNeeded: true
  type: int
  writable: true
- defaultValue:
    value:
      value: MultiVersion
  descriptionHTML: ' '
  legalValues:
  - Exclusive
  - MultiVersion
  name: CachingStrategy
  restartNeeded: true
  type: java.lang.String
  writable: true
- defaultValue:
    value:
      value: 1000
  descriptionHTML: ' '
  name: MaxBeansInCache
  type: int
  writable: true
- creators:
  - weblogic.j2ee.descriptor.wl.MaxCacheSizeBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: MaxCacheSize
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.MaxCacheSizeBean
- defaultValue: {
    }
  descriptionHTML: ' '
  key: true
  name: EntityCacheName
  restartNeeded: true
  type: java.lang.String
  writable: true
