# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.ConfigurationMBean
derivedTypes:
- weblogic.management.configuration.CustomAuthConfigProviderMBean
- weblogic.management.configuration.WLSAuthConfigProviderMBean
descriptionHTML: ' '
name: weblogic.management.configuration.AuthConfigProviderMBean
properties: [
  ]
