# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.ConfigurationMBean
derivedTypes: [
  ]
descriptionHTML: 'Specifies the domain-level deployment configuration attributes. '
name: weblogic.management.configuration.DeploymentConfigurationMBean
properties:
- defaultValue:
    value:
      value: 300
  descriptionHTML: '<p>Specifies the default retire timeout to be used for multi version
    apps. The value is in seconds</p> '
  name: DefaultMultiVersionAppRetireTimeout
  type: int
  writable: true
- defaultValue: {
    }
  descriptionHTML: '<p>Specifies configuration related to deployment-config-overrides.xml</p> '
  exclude: true
  name: DeploymentConfigOverrides
  relationship: containment
  supported: false
  type: weblogic.management.configuration.DeploymentConfigOverridesMBean
- defaultValue:
    value:
      value: 60
  descriptionHTML: 'The maximum number of times the Deployment Service will retry
    sending a message if a connection exception occurs during the during a deployment
    or activate changes operation. '
  name: DeploymentServiceMessageRetryCount
  type: int
  writable: true
- defaultValue:
    value:
      value: 5000
  descriptionHTML: 'The number of milliseconds between retry attempts if a connection
    exception occurs during the during the deployment or activate changes operation. '
  name: DeploymentServiceMessageRetryInterval
  type: int
  writable: true
- defaultValue: {
    }
  descriptionHTML: '<p>Gets the deployment validation plug-in information.</p> '
  name: DeploymentValidationPlugin
  relationship: containment
  type: weblogic.management.configuration.DeploymentValidationPluginMBean
- defaultValue:
    value:
      value: 3
  descriptionHTML: 'The maximum number of times the thread dump generation will be
    retried on a long running Retire operation '
  name: LongRunningRetireThreadDumpCount
  type: int
  writable: true
- defaultValue:
    value:
      value: 60000
  descriptionHTML: 'The number of milliseconds between thread dump retry on a long
    running Retire operation. '
  name: LongRunningRetireThreadDumpInterval
  type: long
  writable: true
- defaultValue:
    value:
      value: 1200000
  descriptionHTML: 'The number of milliseconds a thread dump generation will start
    for a long running Retire operation. '
  name: LongRunningRetireThreadDumpStartTime
  type: long
  writable: true
- defaultValue:
    value:
      value: 2
  descriptionHTML: '<p>Specifies the maximum number of application versions for each
    application.</p> '
  exclude: true
  name: MaxAppVersions
  supported: false
  type: int
  writable: true
- defaultValue:
    value:
      value: 20
  descriptionHTML: '<p>Gets the value of the maximum number of retired tasks to save
    information for.</p> '
  name: MaxRetiredTasks
  type: int
  writable: true
- defaultValue:
    secureModeValue:
      value: false
    value:
      value: false
  descriptionHTML: '<p>Specifies whether the Remote Deployer EJB is automatically
    deployed in the current domain. The Remote Deployer EJB is only used by the weblogic.Deployer
    tool in the WLS 9.0 and 9.1 releases when the -remote option is specified.</p>  <p>If
    the Remote Deployer EJB is not deployed, you will not be able to use the -remote
    option in weblogic.Deployer running in a 9.0 or 9.1 installation. You can still
    use the -remote option from weblogic.Deployer in 9.2 or later releases.</p> '
  name: RemoteDeployerEJBEnabled
  obsolete: 'true'
  restartNeeded: true
  supported: false
  type: boolean
  writable: true
- defaultValue:
    secureModeValue:
      value: false
    value:
      value: false
  descriptionHTML: '<p>Specifies whether applications with staging mode of STAGE are
    restaged only during redeploy operation. If set to true, then applications will
    never restage during server startup and will only be restaged on an explicit redeploy
    operation.</p> '
  name: RestageOnlyOnRedeploy
  restartNeeded: true
  type: boolean
  writable: true
