# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.configuration.ConfigurationMBean
descriptionHTML: 'A Deployment is any MBean that may be deployed on one or more targets,
  such as a Component, a Web Server personality, a JMS Front-end or back-end or a
  JDBC connection pool.  A deployment has targets, which specify which servers the
  deployment should be deployed on. Assigning the targets on a deployment will cause
  the deployment to get deployed on those targets. If the targets overlap, the deployment
  will only be deployed once. For example, if a deployment is deployed both on a cluster
  C and on a server S that is a member of that cluster, the deployment will be deployed
  on S only once.  Simply adding or removing a target will not affect the deployment
  state for this deployment. The user must explicitly activate or deactivate the deployment.  Certain
  types of deployments, ComponentMBeans, behave slightly differently. Please refer
  to their documentation for more information. '
name: weblogic.management.configuration.DeploymentMBean
properties:
- defaultValue:
    value:
      value: 1000
  descriptionHTML: '<p>A priority that the server uses to determine when it deploys
    an item. The priority is relative to other deployable items of the same type.</p>  <p>For
    example, the server prioritizes and deploys all EJBs before it prioritizes and
    deploys startup classes.</p>  <p>Items with the lowest Deployment Order value
    are deployed first. There is no guarantee on the order of deployments with equal
    Deployment Order values. There is no guarantee of ordering across clusters.</p> '
  name: DeploymentOrder
  type: int
  writable: true
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>You must select a target on which an MBean will be deployed
    from this list of the targets in the current domain on which this item can be
    deployed. Targets must be either servers or clusters. The deployment will only
    occur once if deployments overlap.</p> '
  name: Targets
  relationship: reference
  type: weblogic.management.configuration.TargetMBean
  writable: true
