# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.ConfigurationMBean
derivedTypes: [
  ]
descriptionHTML: '<p> The local setting of an HTTP/2 connection on a web server. </p> '
name: weblogic.management.configuration.Http2ConfigMBean
properties:
- defaultValue:
    value:
      value: 4096
  descriptionHTML: '<p> The server''s maximum size of the header compression table
    used to decode header blocks, in octets. </p> '
  name: HeaderTableSize
  type: int
  writable: true
- defaultValue:
    value:
      value: 65535
  descriptionHTML: '<p> The server''s initial window size (in octets) for stream-level
    flow control. This setting affects the window size of all streams. </p> '
  name: InitialWindowSize
  type: int
  writable: true
- defaultValue:
    value:
      value: 300
  descriptionHTML: '<p> The maximum number of concurrent streams that the server will
    allow. This limit is directional: it applies to the number of streams that the
    server permits the receiver to create. </p> '
  name: MaxConcurrentStreams
  type: int
  writable: true
- defaultValue:
    value:
      value: 16384
  descriptionHTML: '<p> The size of the largest frame payload that the server is willing
    to receive, in octets. </p> '
  name: MaxFrameSize
  type: int
  writable: true
- defaultValue:
    value:
      value: 2147483647
  descriptionHTML: '<p> The maximum size of header list that the server is prepared
    to accept, in octets. The value is based on the uncompressed size of header fields,
    including the length of the name and value in octets plus an overhead of 32 octets
    for each header field. </p> '
  name: MaxHeaderListSize
  type: int
  writable: true
