# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.descriptor.SettableBean
derivedTypes: [
  ]
descriptionHTML: ' '
name: weblogic.j2ee.descriptor.wl.WeblogicApplicationBean
properties:
- creators:
  - weblogic.j2ee.descriptor.wl.ApplicationAdminModeTriggerBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ApplicationAdminModeTrigger
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ApplicationAdminModeTriggerBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ApplicationParamBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ApplicationParams
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ApplicationParamBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.CapacityBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Capacities
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.CapacityBean
- defaultValue: {
    }
  descriptionHTML: ' '
  name: CdiDescriptor
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.CdiDescriptorBean
- defaultValue: {
    }
  descriptionHTML: ' '
  name: ClassLoading
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ClassLoadingBean
- creators:
  - weblogic.j2ee.descriptor.wl.ClassloaderStructureBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ClassloaderStructure
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ClassloaderStructureBean
- creators:
  - weblogic.j2ee.descriptor.wl.CoherenceClusterRefBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: CoherenceClusterRef
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.CoherenceClusterRefBean
- defaultValue: {
    }
  descriptionHTML: ' '
  name: ComponentFactoryClassName
  restartNeeded: true
  type: java.lang.String
  writable: true
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ContextRequestClassBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ContextRequests
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ContextRequestClassBean
- creators:
  - weblogic.j2ee.descriptor.wl.EjbBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Ejb
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.EjbBean
- array: true
  defaultValue: {
    }
  descriptionHTML: ' '
  name: EjbReferenceDescriptions
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.EjbReferenceDescriptionBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.FairShareRequestClassBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: FairShareRequests
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.FairShareRequestClassBean
- creators:
  - weblogic.j2ee.descriptor.wl.FastSwapBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: FastSwap
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.FastSwapBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.JDBCConnectionPoolBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: JDBCConnectionPools
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.JDBCConnectionPoolBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.LibraryContextRootOverrideBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: LibraryContextRootOverrides
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.LibraryContextRootOverrideBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.LibraryRefBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: LibraryRefs
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.LibraryRefBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ListenerBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Listeners
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ListenerBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ManagedExecutorServiceBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ManagedExecutorServices
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ManagedExecutorServiceBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ManagedScheduledExecutorServiceBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ManagedScheduledExecutorServices
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ManagedScheduledExecutorServiceBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ManagedThreadFactoryBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ManagedThreadFactories
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ManagedThreadFactoryBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.MaxThreadsConstraintBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: MaxThreadsConstraints
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.MaxThreadsConstraintBean
- array: true
  defaultValue: {
    }
  descriptionHTML: ' '
  name: MessageDestinationDescriptors
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.MessageDestinationDescriptorBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.MinThreadsConstraintBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: MinThreadsConstraints
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.MinThreadsConstraintBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.WeblogicModuleBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Modules
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.WeblogicModuleBean
- creators:
  - weblogic.j2ee.descriptor.wl.OsgiFrameworkReferenceBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: OsgiFrameworkReference
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.OsgiFrameworkReferenceBean
- creators:
  - weblogic.j2ee.descriptor.wl.PreferApplicationPackagesBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: PreferApplicationPackages
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.PreferApplicationPackagesBean
- creators:
  - weblogic.j2ee.descriptor.wl.PreferApplicationResourcesBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: PreferApplicationResources
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.PreferApplicationResourcesBean
- defaultValue: {
    }
  descriptionHTML: 'Gets the Ready App "ready-registration" attribute '
  name: ReadyRegistration
  type: java.lang.String
- array: true
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ResourceDescriptions
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.ResourceDescriptionBean
- array: true
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ResourceEnvDescriptions
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.ResourceEnvDescriptionBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ResponseTimeRequestClassBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ResponseTimeRequests
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ResponseTimeRequestClassBean
- creators:
  - weblogic.j2ee.descriptor.wl.SecurityBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Security
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.SecurityBean
- array: true
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ServiceReferenceDescriptions
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.ServiceReferenceDescriptionBean
- defaultValue: {
    }
  descriptionHTML: ' '
  name: SessionDescriptor
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.SessionDescriptorBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.ShutdownBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Shutdowns
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ShutdownBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.SingletonServiceBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: SingletonServices
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.SingletonServiceBean
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.StartupBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Startups
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.StartupBean
- defaultValue: {
    }
  descriptionHTML: 'Gets the "version" attribute '
  name: Version
  restartNeeded: true
  type: java.lang.String
  writable: true
- array: true
  creators:
  - weblogic.j2ee.descriptor.wl.WorkManagerBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: WorkManagers
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.WorkManagerBean
- creators:
  - weblogic.j2ee.descriptor.wl.XmlBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: Xml
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.XmlBean
