# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.runtime.WebsocketBaseRuntimeMBean
derivedTypes: [
  ]
descriptionHTML: 'MBean used for accessing monitored application properties, such
  as registered endpoints, the number of currently open sessions, the maximal number
  of open sessions since the start of monitoring, and message statistics. '
name: weblogic.management.runtime.WebsocketApplicationRuntimeMBean
properties:
- array: true
  defaultValue: {
    }
  descriptionHTML: 'Get MBeans for currently registered endpoints. '
  name: EndpointMBeans
  relationship: containment
  type: weblogic.management.runtime.WebsocketEndpointRuntimeMBean
roles:
  allowed:
  - Operator
