import { HelpData } from "../typedefs/common";
import { PDJ, Property, Section } from "../typedefs/pdj";
import { PropertyValue, PropertyValueArrayMember, PropertyValueHolder, RDJ, Reference } from "../typedefs/rdj";
import { Model } from "./common";
export type ModelPropertyValue = PropertyValue | PropertyValue[] | File;
export type TokenValue = string;
export type UnresolvedReference = string;
declare enum ENTRY_TYPE {
    REGULAR = 0,
    UNRESOLVED_REF = 1,
    MODEL_TOKEN = 2
}
export declare class FormContentModel extends Model {
    getTypedPropertyValue(propertyName: string, value: ModelPropertyValue): ModelPropertyValue;
    update(): Promise<Response>;
    rowsSelectedForActionInput: Array<string | Reference> | undefined;
    refresh(): Promise<void>;
    changeSlice(sliceName: string): Promise<void>;
    showAdvanced: boolean;
    showInstructions: boolean;
    readonly titlesBeforeProperties: Map<string, string>;
    changes: Map<string, PropertyValueHolder>;
    messages: Map<string, string[]>;
    isActionInput(): boolean;
    isCreate(): boolean;
    isEdit(): boolean;
    isDataMissing(): boolean;
    isCreatableOptionalSingleton(): boolean;
    isNonCreatableOptionalSingleton(): boolean;
    canCreateDashboard(): boolean;
    getDashboardCreateForm(): Reference | undefined;
    getCreateForm(): Reference;
    getSelfResourceData(): string | undefined;
    getSlices(): import("../typedefs/pdj").Slice[] | undefined;
    getNumberOfColumns(): number;
    isDisabled(fieldDescription: Property): boolean;
    isRestartNeeded(fieldDescription: Property): boolean;
    isRequired(fieldDescription: Property): boolean;
    isReadOnly(fieldDescription: Property): boolean;
    getWidth(fieldDescription: Property): string | undefined;
    isFormReadOnly(): boolean;
    isFieldBoolean(fieldDescription: Property): boolean;
    isFieldProperties(fieldDescription: Property): boolean;
    isPolicyExpression(fieldDescription: Property): boolean;
    isFieldFileContents(fieldDescription: Property): boolean;
    isFieldFilename(fieldDescription: Property): boolean;
    isFieldNewFilename(fieldDescription: Property): boolean;
    isSecretField(fieldDescription: Property): boolean;
    isFieldNumber(fieldDescription: Property): boolean;
    isFieldArray(fieldDescription: Property): boolean;
    isFieldSelect(fieldDescription: Property): boolean;
    isFieldMultiSelect(fieldDescription: Property): boolean;
    getSelectionsForProperty(fieldDescription: Property): {
        label: string | undefined;
        value: PropertyValue | PropertyValue[] | File | undefined;
    }[] | undefined;
    getOptionsSources(fieldDescription: Property): Reference[] | undefined;
    constructor(rdj: RDJ, pdj: PDJ);
    getPropertyDescription(propertyName: string): Property | undefined;
    getPropertyDescriptions(): Property[];
    getPlaceHolder(fieldDescription: Property): string | undefined;
    getTitle(fieldDescription: Property): string;
    getHint(fieldDescription: Property): string | number | true | PropertyValueArrayMember | Reference | PropertyValue[] | File;
    getIntroductionHTML(): string;
    getHelpTopics(): import("../typedefs/pdj").HelpTopic[];
    getDetailedHelp(): HelpData[];
    private getOptionForReference;
    private getOptionsForReferenceDynamicEnum;
    getMessages(propertyName: string): string[];
    getPropertyList(): string[];
    hasAdvancedProperties(): boolean;
    getTitleToInsertBeforePropertie(propertyName: string): string | undefined;
    hasSections(): boolean;
    getTopLevelPropertyNames(): string[];
    getVisibleSections(): Section[];
    private _getAllProperties;
    getDefaultValueForProperty(propertyName: string): undefined;
    isPropertyDefaulted(propertyName: string): boolean;
    getProperty(propertyName: string): PropertyValue | PropertyValue[] | File | undefined;
    setPropertyAsTokenValue(propertyName: string, tokenValue: TokenValue): TokenValue;
    setPropertyAsUnresolvedReference(propertyName: string, unresolvedReference: UnresolvedReference): UnresolvedReference;
    setProperty(propertyName: string, propertyValue?: ModelPropertyValue): ModelPropertyValue | undefined;
    _setProperty(entryType: ENTRY_TYPE, propertyName: string, propertyValue?: ModelPropertyValue): ModelPropertyValue | undefined;
    resetProperty(propertyName: string): void;
    clear(): void;
    clearChanges(): void;
    clearMessages(): void;
    getChanges(): Record<string, PropertyValueHolder>;
    hasChanges(): boolean;
    hasPropertyChanged(propertyName: string): boolean;
    getCompensatingPayload(): void;
    clone(): any;
}
export {};
