#!/bin/bash
targetdir="$1"
shift
mkdir -p "$targetdir"
for i
do
  case "$i" in
  *frontend_*)
    target="$targetdir/electron_${i##*frontend_}"
    ;;
  *)
    target="$targetdir/electron.properties"
  esac
  if ! egrep '^wrc-electron|^wrc-common' $i > "$target"
  then
    echo No Electron strings in $i, skipping
    rm -f "$target"
  fi
done
