#!/bin/bash
set -e
if [ -z "$JAVA_HOME" ]
then
  echo JAVA_HOME must be set >&2
  exit 1
fi
case "$0" in
/*)
  cd "${0%/*}"
  ;;
*/*)
  cd ./"${0%/*}"
esac
if [ ! -f ../runnable/console.jar ]
then
  echo Please do a make before running quick-run >&2
  exit 1
fi
if [ -n "$https_proxy" ]
then
  export ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=$https_proxy
fi
if [ ! -d node_modules ]
then
  npm install
fi
case "$(uname -s)" in
*arwin)
  DISTDIR=node_modules/electron/dist/Electron.app/Contents/MacOS
  ;;
*)
  DISTDIR=node_modules/electron/dist
esac

mkdir -p $DISTDIR

if [ ! -r $DISTDIR/customjre ]
then
  ln -s "$JAVA_HOME" $DISTDIR/customjre
fi
if [ ! -r $DISTDIR/backend ]
then
  ln -s "${PWD%/*}/runnable" $DISTDIR/backend
fi
cp -f "$PWD"/package.json "$DISTDIR"
npm start -- "$@"
