# Copyright (c) 2020, 2023, Oracle and/or its affiliates.

console:
  name: "Oracle WebLogic Server Remote Console"
  version: "2.0"
  connectTimeoutMillis: 10000
  readTimeoutMillis: 20000
  disableHostnameVerification: false
  enableSameSiteCookieValue: false
  valueSameSiteCookie: "Lax"
  ssoTimerSeconds: 30
  ssoTimeoutSeconds: 300
