import { h } from 'preact';
import { Dispatch } from "preact/hooks";
import { ojInputText } from "ojs/ojinputtext";
import { ojSwitch } from "ojs/ojswitch";
import { FormContentModel } from "../../shared/model/formcontentmodel";
import { Property } from "../../shared/typedefs/pdj";
import "oj-c/input-password";
import "oj-c/button";
import "oj-c/input-text";
import "css!wrc/shared/shared-styles.css";
type FieldProps = {
    fieldDescription: Property;
    formModel: FormContentModel;
};
export declare const getLabel: (fieldDescription: Property, formModel: FormContentModel) => h.JSX.Element | null;
export declare const getArrayInputField: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const getSecretInputField: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const getInputField: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const getPropertiesEditor: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged | ojSwitch.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const getMultiSelectBox: (fieldDescription: Property, formModel: FormContentModel, changeNotifier: () => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const MoreMenu: ({ fieldDescription, formModel }: FieldProps) => h.JSX.Element;
export declare const getSelectSingle: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const getFileSelector: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel: any) => h.JSX.Element;
export declare const getFileSelectorForFilename: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel: any) => h.JSX.Element;
export declare const getFileSelectorForNewFile: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel: any) => h.JSX.Element;
export declare const getSwitch: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (event: ojInputText.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export declare const getPolicyExpression: (fieldDescription: Property, formModel: FormContentModel, valueChangedHandler: (e: ojInputText.valueChanged) => void, setModel?: Dispatch<FormContentModel>) => h.JSX.Element;
export {};
