# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.runtime.RuntimeMBean
descriptionHTML: '<p>This MBean is the user API for monitoring deployment operations
  and exists only on an Administration Server. Currently only start and stop operations
  initiated by AppDeploymentRuntimeMBean are supported.</p> '
name: weblogic.management.runtime.DeploymentProgressObjectMBean
properties:
- defaultValue: {
    }
  descriptionHTML: '<p>The AppDeploymentMBean for the current deployment operation.</p> '
  excludeFromRest: work around bug 20088067
  name: AppDeploymentMBean
  relationship: reference
  supported: false
  type: weblogic.management.configuration.AppDeploymentMBean
- defaultValue: {
    }
  descriptionHTML: '<p>The name of the application for the current deployment operation.</p> '
  name: ApplicationName
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: '<p>The time that the current deployment operation began. The value
    is in milliseconds consistent with the system time.</p> '
  name: BeginTime
  type: long
- defaultValue: {
    }
  descriptionHTML: '<p>The task associated with the deployment operation</p> '
  exclude: true
  name: DeploymentTaskRuntime
  relationship: containment
  supported: false
  type: weblogic.management.runtime.DeploymentTaskRuntimeMBean
- defaultValue: {
    }
  descriptionHTML: '<p>The time that the current deployment operation ended. The value
    is in milliseconds consistent with the system time. If the operation has not ended,
    the value will be zero.</p> '
  name: EndTime
  type: long
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>The targets on which the current deployment operation failed.</p> '
  name: FailedTargets
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: '<p>The unique ID for the current deployment operation.</p> '
  name: Id
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: '<p>Return the LibraryMBean for the current deployment operation.</p> '
  excludeFromRest: work around bug 20088067
  name: LibraryMBean
  relationship: reference
  supported: false
  type: weblogic.management.configuration.LibraryMBean
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>Provides an ordered array of status messages generated for
    the current deployment operation.</p> '
  name: Messages
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: '<p>The deployment operation type for the current deployment operation.
    Possible values are 1 (start) and 2 (stop).</p> '
  name: OperationType
  type: int
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>If the current deployment operation has failed, this method
    may return zero or more exception(s) which represent the root cause of the failure.
    The array will not contain WLS exception classes; instead they will be new Exceptions
    containing the stack traces and messages from the original WLS Exceptions.</p> '
  name: RootExceptions
  type: java.lang.RuntimeException
- defaultValue: {
    }
  descriptionHTML: '<p>The state of the current deployment operation. Possible values
    are STATE_INITIALIZED, STATE_RUNNING, STATE_COMPLETED, STATE_FAILED and STATE_DEFERRED.</p> '
  name: State
  type: java.lang.String
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>The targets specified for the current deployment operation.</p> '
  name: Targets
  type: java.lang.String
roles:
  allowed:
  - Deployer
