# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.ConfigurationMBean
derivedTypes: [
  ]
descriptionHTML: 'A System Component Configuration MBean allows configuration to be
  shared between one or more System Components. '
name: weblogic.management.configuration.SystemComponentConfigurationMBean
properties:
- defaultValue: {
    }
  descriptionHTML: 'Get the system component type Examples of types may include "OHS",
    "Coherence". New System Components may be added in the future so the list of types
    is not static. '
  name: ComponentType
  restartNeeded: true
  type: java.lang.String
  writable: true
- defaultValue:
    derivedDefault: true
  descriptionHTML: 'Get the source path for configuration files Note: if you use a
    SystemComponentConfiguration, then the files for the SystemComponents directory
    are not used so there is no chance of conflict. '
  name: SourcePath
  restartNeeded: true
  type: java.lang.String
  writable: true
- array: true
  defaultValue: {
    }
  descriptionHTML: 'System Component Configurations are targeted to System Component
    instances. '
  name: SystemComponents
  relationship: reference
  type: weblogic.management.configuration.SystemComponentMBean
  writable: true
