# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.runtime.RuntimeMBean
derivedTypes: [
  ]
descriptionHTML: '<p>Encapsulates runtime policy subject information about a particular
  Web Service reference. The name attribute of this MBean will be the value of the
  service-ref-name element in service reference descriptor file or the name attribute
  value of WebServiceRef annotation.</p> '
name: weblogic.management.runtime.WseeClientConfigurationRuntimeMBean
properties:
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>Specifies the list of port configurations that are associated
    with this Web Service reference.</p> '
  name: Ports
  relationship: containment
  type: weblogic.management.runtime.WseePortConfigurationRuntimeMBean
- defaultValue: {
    }
  descriptionHTML: '<p>Specifies the qualified name of this client configuration.</p>  <p>This
    attribute is grabbed from service reference descriptor bean.</p> '
  name: ServiceReferenceName
  type: java.lang.String
