# Copyright 2020, 2021, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

---
- id: default
  name: domain1
  version: 14.1.1.0.0
  username: weblogic
  listenAddress: localhost
  listenPort: 7001
  isDefault: true
- id: Conn1
  name: jrf_domain
  version: 14.1.1.0.0
  username: weblogic
  listenAddress: slc15bju.us.oracle.com
  listenPort: 7201
  isDefault: false
- id: Conn2
  name: base_domain
  version: 14.1.1.0.0
  username: weblogic
  listenAddress: den01sza.us.oracle.com
  listenPort: 7010
  isDefault: false
