# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.configuration.DeploymentMBean
descriptionHTML: '<p>Temporary MBean for startup and shutdown classes. In the near
  future these will be turned into components.</p> '
name: weblogic.management.configuration.ClassDeploymentMBean
properties:
- defaultValue: {
    }
  descriptionHTML: '<p>Arguments that a server uses to initialize a class.</p>  <p>Separate
    multiple arguments with a comma. For example:</p>  <p><code>first=MyFirstName,last=MyLastName</code></p> '
  name: Arguments
  restartNeeded: true
  type: java.lang.String
  writable: true
- defaultValue:
    derivedDefault: true
  descriptionHTML: '<p>The fully qualified name of a class to load and run. The class
    must be on the server''s classpath.</p>  <p>For example, <code>mycompany.mypackage.myclass</code></p> '
  name: ClassName
  nullable: true
  restartNeeded: true
  type: java.lang.String
  writable: true
