# Copyright (c) 2023, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: []
baseTypes:
- weblogic.management.runtime.RuntimeMBean
derivedTypes: []
name: weblogic.management.runtime.DeploymentPlanRuntimeMBean
roles:
  allowed:
  - Deployer
  - Operator
properties:
- name: Deployment
  type: weblogic.management.descriptor.DeploymentDBean
  relationship: containment
- name: Name
  type: java.lang.String
  descriptionHTML: Gets the "application-name" element
- name: Description
  type: java.lang.String
  descriptionHTML: Gets the "description" element
- name: Version
  type: java.lang.String
  descriptionHTML: Gets the "version" element
- name: PlanPath
  type: java.lang.String
  descriptionHTML: >
    The fully resolved location of this application's deployment plan on the Administration Server.
#- name: ConfigRoot
#  type: java.lang.String
#  descriptionHTML: Gets the "config-root" element
- name: DeploymentPlan
  type: java.lang.String
  writable: true
  descriptionHTML: The deployment plan's contents, as xml
  setRoles:
    allowed:
    - Deployer
    - Operator
- name: VariableAssignments
  relationship: containment
  type: weblogic.management.runtime.VariableAssignmentRuntimeMBean
  array: true
  descriptionHTML: Gets all of the variable assignments in this deployment plan.
#- name: Variables
#  relationship: containment
#  type: weblogic.management.runtime.VariableRuntimeMBean
#  array: true
#  descriptionHTML: Gets array of all "variable" elements
#- name: Modules
#  relationship: containment
#  type: weblogic.management.runtime.ModuleOverrideRuntimeMBean
#  array: true
#  descriptionHTML: Gets array of all "module-override" elements
