# Copyright (c) 2024, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.descriptor.DeploymentDBean
name: weblogic.management.descriptor.EjbJarDeploymentDBean
properties:
- name: Ejbs
  type: weblogic.management.descriptor.EjbDBean
  array: true
  relationship: containment