# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

name: weblogic.management.security.credentials.UserPasswordCredentialMapperJDBCApplicationMBean
baseTypes:
- weblogic.management.security.credentials.UserPasswordCredentialMapperResourceMBean

properties:
- name: Name
  type: java.lang.String
  descriptionHTML: "The name of the JDBC application."
- name: ResourceId
  type: java.lang.String
  descriptionHTML: "The security resource identifier corresponding to the JDBC application."
- name: CredentialMappings
  relationship: containment
  type: weblogic.management.security.credentials.JDBCApplicationUserPasswordCredentialMappingMBean
  array: true
- name: Credentials
  relationship: containment
  type: weblogic.management.security.credentials.JDBCApplicationUserPasswordCredentialMBean
  array: true
