# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes: [
  ]
derivedTypes: [
  ]
descriptionHTML: ' '
name: weblogic.j2ee.descriptor.wl.ApplicationPoolParamsBean
properties:
- creators:
  - weblogic.j2ee.descriptor.wl.XAParamsBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: XAParams
  relationship: containment
  supported: false
  type: weblogic.j2ee.descriptor.wl.XAParamsBean
- defaultValue: {
    }
  descriptionHTML: ' '
  name: LoginDelaySeconds
  type: int
  writable: true
- defaultValue: {
    }
  descriptionHTML: ' '
  name: JDBCXADebugLevel
  type: int
  writable: true
- defaultValue: {
    }
  descriptionHTML: ' '
  name: LeakProfilingEnabled
  restartNeeded: true
  type: boolean
  writable: true
- creators:
  - weblogic.j2ee.descriptor.wl.ConnectionCheckParamsBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: ConnectionCheckParams
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.ConnectionCheckParamsBean
- creators:
  - weblogic.j2ee.descriptor.wl.SizeParamsBean
  defaultValue: {
    }
  descriptionHTML: ' '
  name: SizeParams
  relationship: containment
  type: weblogic.j2ee.descriptor.wl.SizeParamsBean
- defaultValue: {
    }
  descriptionHTML: ' '
  name: RemoveInfectedConnectionsEnabled
  restartNeeded: true
  type: boolean
  writable: true
