# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.ConfigurationMBean
derivedTypes:
- weblogic.management.configuration.SystemResourceMBean
descriptionHTML: 'This MBean is a reference to a system configuration extension. '
name: weblogic.management.configuration.ConfigurationExtensionMBean
properties:
- defaultValue:
    derivedDefault: true
  descriptionHTML: '<p>The name of the file that contains the module. By default the
    file resides in the DOMAIN_DIR/config directory.</p> <p>By default, the file name
    is derived from the bean name using the following pattern:</p> <p> &lt;beanName&gt;.xml
    </p> <p>Note that this is a read-only property that can only be set when the bean
    is created.</p> '
  name: DescriptorFileName
  type: java.lang.String
