# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.ConfigurationMBean
derivedTypes:
- weblogic.management.configuration.DomainMBean
- weblogic.management.configuration.ServerTemplateMBean
- weblogic.management.configuration.PartitionMBean
descriptionHTML: 'The ConfigurationPropertiesMBean is used when performing macro substitution
  from elements in the ServerTemplateMBeans or ResourceGroupTemplateMBean. If a macro
  is encountered in the template attribute, then the macro name will be used to locate
  the corresponding ConfigurationPropertyMBean in a parent MBean. This may be at the
  Partition, Server, ServerTemplate or Domain level. If found, the value will be substituted
  accordingly. '
name: weblogic.management.configuration.ConfigurationPropertiesMBean
properties:
- array: true
  creators:
  - weblogic.management.configuration.ConfigurationPropertyMBean
  defaultValue: {
    }
  descriptionHTML: '<p>Specifies the list of properties that are associated with this
    container object.</p> '
  name: ConfigurationProperties
  relationship: containment
  type: weblogic.management.configuration.ConfigurationPropertyMBean
