# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.runtime.RuntimeMBean
derivedTypes: [
  ]
descriptionHTML: 'The runtime MBean for the JAX-RS application resource config. '
name: weblogic.management.runtime.JaxRsResourceConfigTypeRuntimeMBean
properties:
- defaultValue: {
    }
  descriptionHTML: '<p>Provides the class name of the JAX-RS application resource
    configuration.</p> '
  name: ClassName
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: '<p>Provides the properties of the Jax-Rs application resource
    configuration</p> '
  name: Properties
  type: java.util.Properties
roles:
  allowed:
  - Operator
