# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.configuration.SNMPAgentMBean
- weblogic.management.configuration.DeploymentMBean
derivedTypes: [
  ]
descriptionHTML: '<p>This MBean is an SNMP agent that can be targeted to instances
  of WebLogic Server. </p> <p>With SNMP, you configure <b>agents</b> to gather and
  send data about managed resources in response to a request from <b>managers</b>.
  You can also configure agents to issue unsolicited reports to managers when they
  detect predefined thresholds or conditions on a managed resource.</p> <p>In a WebLogic
  Server domain, you can choose a centralized or de-centralized model for SNMP monitoring
  and communication:</p> <ul><li>In a centralized model, you create an instance of
  this MBean and target it only to the Administration Server. This agent communicates
  with all Managed Servers in the domain. SNMP managers communicate only with the
  SNMP agent on the Administration Server. This model is convenient but introduces
  performance overhead in WebLogic Server. In addition, if the Administration Server
  is unavailable, you cannot monitor the domain through SNMP.</li> <li>In a de-centralized
  model, you create an instance of this MBean and target it to each Managed Server
  that you want to monitor. (Alternatively, you can create multiple instances of this
  MBean and target each instance to an individual Managed Server.) Your SNMP manager
  must communicate with the agents on individual Managed Servers.</li></ul> <p>To
  support domains that were created with WebLogic Server release 9.2 and earlier,
  a domain also hosts a singleton SNMP agent whose scope is the entire domain (see
  SNMPAgentMBean). SNMPAgentMBean offers the same features as an instance of this
  MBean (SNMPAgentDeploymentMBean) that you have targeted as described in the centralized
  model above. However, the underlying implementation of SNMPAgentMBean is different
  and it will eventually be deprecated. SNMPAgentMBean is overridden if you target
  an instance of this MBean to the Administration Server.</p> '
name: weblogic.management.configuration.SNMPAgentDeploymentMBean
properties: [
  ]
