# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.diagnostics.descriptor.WLDFBean
descriptionHTML: '<p> Parent interface of all child beans of WLDFConfigurationPropertiesBean.
  </p> '
name: weblogic.diagnostics.descriptor.WLDFConfigurationPropertyBean
roles:
  allowed:
  - Deployer
