# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.diagnostics.descriptor.WLDFConfigurationPropertyBean
derivedTypes: [
  ]
descriptionHTML: '<p>Represents a set of WLDFPropertyBean and WLDFEncryptedPropertyBean
  instances, akin to a <code>java.util.Properties</code> object.</p> '
name: weblogic.diagnostics.descriptor.WLDFConfigurationPropertiesBean
properties:
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>Returns the list of all WLDFPropertyBean and WLDFEncryptedPropertyBean
    objects that are associated with this container object.</p> '
  name: ConfigurationProperties
  relationship: containment
  type: weblogic.diagnostics.descriptor.WLDFConfigurationPropertyBean
- array: true
  creators:
  - weblogic.diagnostics.descriptor.WLDFEncryptedPropertyBean
  defaultValue: {
    }
  descriptionHTML: 'Returns all the encrypted properties for the action. '
  name: EncryptedProperties
  relationship: containment
  type: weblogic.diagnostics.descriptor.WLDFEncryptedPropertyBean
- array: true
  creators:
  - weblogic.diagnostics.descriptor.WLDFPropertyBean
  defaultValue: {
    }
  descriptionHTML: 'Returns all WLDFPopertyBean instances. '
  name: Properties
  relationship: containment
  type: weblogic.diagnostics.descriptor.WLDFPropertyBean
roles:
  allowed:
  - Deployer
