# Copyright (c) 2020, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

actions: [
  ]
baseTypes:
- weblogic.management.runtime.RuntimeMBean
derivedTypes: [
  ]
descriptionHTML: '<p> Encapsulates runtime information about a particular operation.
  The subject name attribute of this MBean will be the value of the local part of
  operation QName. </p> '
name: weblogic.management.runtime.WseeOperationConfigurationRuntimeMBean
properties:
- defaultValue: {
    }
  descriptionHTML: 'Get attachment support for this operation MBean. '
  name: PolicyAttachmentSupport
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: 'Get subject name for this operation MBean. '
  name: PolicySubjectName
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: 'The policySubject parameter must uniquely identify what application,
    module, service, and port (port or operation for WLS Policy) is targeted. The
    syntax currently used by JRF for Java EE Webservice Endpoints will be used: /{domain}/{instance}/{app}/WEBs|EJBs/{module
    }/WEBSERVICECLIENTs/{service-ref-name}/PORTs/{port}/OPERATIONs/{operation} '
  name: PolicySubjectResourcePattern
  type: java.lang.String
- defaultValue: {
    }
  descriptionHTML: 'Get subject type for this operation MBean. '
  name: PolicySubjectType
  type: java.lang.String
