# Copyright 2023,2024, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

appMenu:
  - id: appMenu
    class: cfe-app-menu-launcher
    launcher: appMenuLauncher
    iconClass: oj-ux-ico-apps-grid
    visible: true
    disabled: false
    menuItems:
      - id: about
        label: About WebLogic Remote Console
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: settings
        label: Settings...
        accelerator: Meta|,
        visible: true
        disabled: false
      - id: preferences
        label: Application Preferences...
        accelerator: Meta|,
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: checkForUpdates
        label: Check for Updates...
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: quitApps
        label: Quit WebLogic Remote Console
        visible: true
        disabled: false
  - id: fileMenu
    class: cfe-app-menu-launcher
    launcher: fileMenuLauncher
    label: File
    visible: true
    disabled: false
    menuItems:
      - id: newWindow
        label: New Window
        accelerator: Control|Alt|N
        visible: true
        disabled: false
      - id: closeWindow
        label: Close Window
        accelerator: Shift|Meta|W
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: projects
        label: Projects
        visible: true
        disabled: false
        menu:
          - id: projectsMenu
            menuItems:
              - id: newProject
                label: New Project...
                visible: true
                disabled: false
              - id: recentProject
                label: Recent Project
                visible: true
                disabled: false
                menu:
                  - id: recentProjectsMenu
                    menuItems:
                      - id: myproject14
                        label: 'My Project 14'
                        visible: true
                        disabled: false
                      - id: myproject27
                        label: 'My Project 27'
                        visible: true
                        disabled: false
              - id: renameProject
                label: 'Rename 1412wls'
                visible: true
                disabled: false
              - id: deleteProject
                label: Delete Project
                visible: true
                disabled: false
                menu:
                  - id: deleteProjectMenu
                    menuItems:
                      - id: myproject20
                        label: 'My Project 20'
                        visible: true
                        disabled: false
                      - id: myproject27
                        label: 'My Project 27'
                        visible: true
                        disabled: false
                      - id: myproject49
                        label: 'My Project 49'
                        visible: true
                        disabled: false
              - id: closeProject
                label: Close Project
                visible: true
                disabled: false
              - label: "---"
                visible: true
              - id: 'load-project'
                label: Import Project...
                visible: true
                disabled: false
              - id: 'export-all-to-project'
                label: Export Project...
                visible: true
                disabled: true
      - id: providers
        label: Providers
        visible: true
        disabled: false
        menu:
          - id: providersMenu
            menuItems:
              - id: 'add-domain-connection'
                label: 'Add Admin Server Connection...'
                visible: true
                disabled: false
              - label: "---"
                visible: true
              - id: 'add-existing-wdt-model'
                label: 'Add WDT Model File...'
                visible: true
                disabled: false
              - id: 'add-wdt-composite'
                label: 'Add WDT Composite Model File...'
                visible: true
                disabled: false
              - label: "---"
                visible: true
              - id: 'add-existing-property-list'
                label: 'Add Properties List File...'
                visible: true
                disabled: false
              - label: "---"
                visible: true
              - id: 'add-new-wdt-model'
                label: 'Create Provider for New WDT Model File...'
                visible: true
                disabled: false
              - id: 'add-new-property-list'
                label: 'Create Provider for New Properties List File...'
                visible: true
                disabled: false
  - id: editMenu
    class: cfe-app-menu-launcher
    launcher: editMenuLauncher
    label: Edit
    visible: true
    disabled: true
    menuItems:
      - id: undo
        label: Undo
        accelerator: Meta|Z
        visible: true
        disabled: true
      - id: redo
        label: Redo
        accelerator: Shift|Meta|Z
        visible: true
        disabled: true
      - label: "---"
        visible: true
      - id: cut
        label: Cut
        accelerator: Meta|X
        visible: true
        disabled: true
      - id: copy
        label: Copy
        accelerator: Meta|C
        visible: true
        disabled: true
      - id: paste
        label: Paste
        accelerator: Meta|V
        visible: true
        disabled: true
      - id: selectAll
        label: Select All
        accelerator: Meta|A
        visible: true
        disabled: true
      - label: "---"
        visible: true
      - id: find
        label: Find in Page
        accelerator: Meta|F
        visible: true
        disabled: false
      - id: findNext
        label: Find Next in Page
        accelerator: Meta|G
        visible: true
        disabled: false
  - id: viewMenu
    class: cfe-app-menu-launcher
    launcher: viewMenuLauncher
    label: View
    visible: true
    disabled: false
    menuItems:
      - id: toggleFullScreen
        label: Enter Full Screen
        accelerator: Meta|R
        visible: true
        disabled: true
  - id: goMenu
    class: cfe-app-menu-launcher
    launcher: goMenuLauncher
    label: Go
    visible: true
    disabled: false
    menuItems:
      - id: providersDrawer
        label: Providers Drawer
        accelerator: Control|Option|P
        visible: true
        disabled: false
      - id: shoppingCartDrawer
        label: Shopping Cart Drawer
        accelerator: Control|Option|S
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: messageCenter
        label: Message Center
        accelerator: Control|Option|M
        visible: false
        disabled: false
      - id: startUpTask
        label: Startup Task
        accelerator: Control|Option|\
        visible: true
        disabled: true
  - id: scriptMenu
    class: cfe-app-menu-launcher
    launcher: scriptMenuLauncher
    label: Script
    visible: true
    disabled: true
    menuItems:
      - id: startRecording
        label: Start Recording
        visible: true
        disabled: true
      - id: stopRecording
        label: Stop Recording
        visible: true
        disabled: true
  - id: tableMenu
    class: cfe-app-menu-launcher
    launcher: tableMenuLauncher
    label: Table
    visible: true
    disabled: false
    menuItems:
      - id: customizeTable
        label: Customize
        accelerator: Control|Option|Z
        visible: true
        disabled: false
      - label: "---"
        visible: false
      - id: copyTable
        label: Copy
        visible: false
        disabled: false
        menu:
          - id: copyTableMenu
            menuItems:
              - id: copyText
                label: As Text
                visible: false
                disabled: false
              - id: copyJSON
                label: As JSON
                visible: false
                disabled: false
              - id: copyYAML
                label: As YAML
                visible: false
                disabled: false
      - id: exportTable
        label: Export
        visible: false
        disabled: false
        menu:
          - id: exportTableMenu
            menuItems:
              - id: exportText
                label: Text...
                visible: false
                disabled: false
              - id: exportJSON
                label: JSON...
                visible: false
                disabled: false
              - id: exportYAML
                label: YAML...
                visible: false
                disabled: false
  - id: windowMenu
    class: cfe-app-menu-launcher
    launcher: windowMenuLauncher
    label: Window
    visible: true
    disabled: false
    menuItems:
      - id: resetWindow
        label: Reset
        accelerator: 'Meta|R'
        visible: true
        disabled: false
  - id: helpMenu
    class: cfe-app-menu-launcher
    launcher: helpMenuLauncher
    label: Help
    visible: true
    disabled: false
    menuItems:
      - id: appDocumentation
        label: WebLogic Remote Console Documentation
        visible: true
        disabled: false
      - id: visitGithubProject
        label: Visit WebLogic Remote Console Github Project
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: whatsNew
        label: What's New
        visible: true
        disabled: false
      - id: changeLogs
        label: Change Logs
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: howdoi
        label: How Do I...
        visible: true
        disabled: false
      - id: tipsDrawer
        label: Tips Drawer
        accelerator: Control|Option|T
        visible: true
        disabled: false
      - label: "---"
        visible: true
      - id: bugsAndFeedback
        label: Report Bug/Leave Feedback
        visible: true
        disabled: false
      - label: "---"
        visible: false
      - id: developerTools
        label: Developer Tools
        accelerator: Alt|Meta|I
        visible: false
        disabled: false