# Copyright 2022, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

name: WebLogic Remote Console
version: '2.4.8'
kind: remote
console-backend:
  name: Oracle WebLogic Console Backend Microprofile Server
  version: '1.0'
  baseUrl: 'http://localhost:8012'
  basePath:
  pollingMillis: 60000
  retryAttempts: 5
  docs: 'https://oracle.github.io/weblogic-remote-console/'
  whatsnew: 'https://github.com/oracle/weblogic-remote-console/releases/tag/v2.4.7'
  services:
    - id: configuration
      path: /configuration
      enabled: true
      components:
        data: null
        pages: null
        changeManager:
          - id: view
            uri: /changeManager
          - id: edit
            uri: /changeManager/changes
          - id: commit
            uri: /changeManager/activate
          - id: discard
            uri: /changeManager/cancelEdit
    - id: monitoring
      path: /monitoring
      enabled: true
      components:
        data: null
        pages: null
        lifecycle:
          - id: view
            prefix: /data
            uri: /DomainRuntime/ServerStates
    - id: information
      path: /about
    - id: connecting
      path: /connection
    - id: providers
      path: /providers
    - id: token
      path: /token
accelerators:
  linux:
    Shift:
      text: 'Shift'
    Control:
      text: 'Ctrl'
    Atl:
      text: 'Alt'
    Meta:
      text: 'Meta'
  windows:
    Shift:
      text: 'Shift'
    Control:
      text: 'Ctrl'
    Atl:
      text: 'Alt'
    Meta:
      icon: 'windows-command-wht_24x24'
  macOS:
    Shift:
      icon: 'macOS-shift-wht_24x24'
    Control:
      icon: 'macOS-control-wht_24x24'
    Atl:
      icon: 'macOS-option-wht_24x24'
    Meta:
      icon: 'macOS-command-wht_24x24'
shortcutKeys:
  - id: appMenu
    label: 'Application Menu Icon'
    key: '/'
  - id: appProfile
    label: 'Application Profiles Selector'
    key: '='
  - id: simpleSearch
    label: 'Simple Search Field'
    key: 'K'
  - id: settings
    label: 'Application Profiles Settings Tab'
    key: ','
  - id: preferences
    label: 'Application Profiles Settings Tab'
    key: '.'
  - id: verticalGripper
    label: 'Provider Tree Resizing Gripper'
    key: '\\'
  - id: navstrip
    label: 'Provider Trees Menu'
    key: 'M'
  - id: navtree
    label: 'Tree Navigator'
    key: 'N'
  - id: landing
    label: 'Tree Landing Page'
    key: 'L'
  - id: home
    label: 'Home Button'
    key: 'H'
  - id: providerManagement
    label: 'Providers Drawer'
    key: 'P'
  - id: table
    label: 'Content Area Table'
    key: 'T'
  - id: form
    label: 'Content Area Form'
    key: 'F'
  - id: tabstrip
    label: 'Form Tabstrip'
    key: ']'
  - id: showAdvancedFields
    label: 'Show Advanced Fields Checkbox'
    key: '['
  - id: breadcrumbs
    label: 'Breadcrumbs Row'
    key: ';'
preferences:
  general:
    theme: light
  navtree:
    useTreeMenusAsRootNodes: false
  providerManagement:
    location: kiosk
    newModel:
      domain:
        fileContents: |
          domainInfo:
            AdminUserName: '@@PROP:ADMIN_USERNAME@@'
            AdminPassword: '@@PROP:ADMIN_PASSWORD@@'
          topology:
            Server:
              AdminServer:
      sparse:
        fileContents: |
          domainInfo:
  startup:
    task:
      default: choose
      #      project:
      #        name: "(Unnamed Project)"
      #        isDefault: true
      #        dataProviders:
      #          - name: Default AdminServer Connection
      #            type: adminserver
      #            username: weblogic
      #            url: "http://localhost:7001"
      # Legal values are: 'use-dialog', 'use-cards'
      chooser: 'use-dialog'
features:
  appMenu:
    disabled: true
  appProfiles:
    disabled: true
  appAlerts:
    disabled: true
  theme:
    disabled: true
  whatsNew:
    disabled: true
  howDoI:
    disabled: true
  iconbarIcons:
    relocated: true
settings:
  logging:
    logFailureResponses: true
    defaultLevel: ERROR
  autoSync:
    minimumSecs: 30
  autoDownloadTimer:
    minimumSecs: 1
  notifications:
    showPopupForFailureResponses: true
    autoCloseInterval: 5000
  sso:
    tokenClockSkew: 180
    maxPollCount: 1800
    domainLoginUri: '/console/login'
