# Copyright 2020, 2021, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

#startup:
#  perspective: landing/configuration
general:
  theme: light
notifications:
  showPopupForFailureResponses: true
  autoCloseInterval: 5000
logging:
  logFailureResponses: true
