name: WebLogic Remote Console
version: '2.4.7'
console-backend:
  name: Oracle WebLogic Console Backend Microprofile Server
  version: '1.0'
  baseUrl: 'http://localhost:8012'
  pollingMillis: 60000
  retryAttempts: 5
  docs: 'https://oracle.github.io/weblogic-remote-console/'
  services:
    - id: configuration
      path: /configuration
      enabled: true
      components:
        data: null
        pages: null
        changeManager:
          - id: view
            uri: /changeManager
          - id: edit
            uri: /changeManager/changes
          - id: commit
            uri: /changeManager/activate
          - id: discard
            uri: /changeManager/cancelEdit
    - id: monitoring
      path: /monitoring
      enabled: true
      components:
        data: null
        pages: null
        lifecycle:
          - id: view
            prefix: /data
            uri: /DomainRuntime/ServerStates
    - id: information
      path: /about
    - id: connecting
      path: /connection
    - id: providers
      path: /providers
    - id: token
      path: /token
preferences:
  themes:
    dark:
      - '#413e3c'
      - '#624f4f'
    light:
      - '#dcd6d1'
      - '#b6a29a'
  shoppingcart:
    location: 'content-area-body'
  recentPages:
    location: 'content-area-body'
  providerManagement:
    location: kiosk
    newModel:
      domain:
        fileContents: |
          domainInfo:
            AdminUserName: '@@PROP:ADMIN_USERNAME@@'
            AdminPassword: '@@PROP:ADMIN_PASSWORD@@'
          topology:
            Server:
              AdminServer:
      sparse:
        fileContents: |
          domainInfo:
  startup:
    task:
      default: choose
      #      project:
      #        name: "(Unnamed Project)"
      #        isDefault: true
      #        dataProviders:
      #          - name: Default AdminServer Connection
      #            type: adminserver
      #            username: weblogic
      #            url: "http://localhost:7001"
      # Legal values are: 'use-dialog', 'use-cards'
      chooser: 'use-dialog'
settings:
  logging:
    defaultLevel: ERROR
  autoSync:
    minimumSecs: 30
  autoDownloadTimer:
    minimumSecs: 1
  sso:
    maxPollCount: 1800
    domainLoginUri: ''
  actions:
    - id: start
      iconFile: action-start-icon-blk_24x24
    - id: startActions
      iconFile: action-start-icon-blk_24x24
    - id: resume
      iconFile: action-resume-icon-blk_24x24
    - id: suspendActions
      iconFile: action-suspend-icon-blk_24x24
    - id: shutdownActions
      iconFile: action-stop-icon-blk_24x24
    - id: restartSSL
      iconFile: action-restart-icon-blk_24x24
    - id: stop
      iconFile: action-stop-icon-blk_24x24
    - id: stopActions
      iconFile: action-stop-icon-blk_24x24
    - id: download
      iconFile: action-download-icon-blk_24x24
    - id: shrink
      iconFile: action-shrink-icon-blk_24x24
    - id: reset
      iconFile: action-reset-icon-blk_24x24
    - id: clearStatementCache
      iconFile: action-clear-icon-blk_24x24
    - id: pauseActions
      iconFile: action-pause-icon-blk_24x24
    - id: resumeActions
      iconFile: action-resume-icon-blk_24x24
    - id: forceCommitSelectedTransactions
      iconFile: action-commit-icon-blk_24x24
    - id: forceRollbackSelectedTransactions
      iconFile: action-rollback-icon-blk_24x24
    - id: deleteActions
      iconFile: delete-icon-blk_24x24
    - id: exportActions
      iconFile: action-export-3d-icon-blk_24x24
    - id: importMessages
      iconFile: action-import-3d-icon-blk_24x24
    - id: edit
      iconFile: action-edit-icon-blk_24x24
    - id: redeploy
      iconFile: action-redeploy-icon-blk_24x24
    - id: update
      iconFile: action-upload-icon-blk_24x24
    - id: createPlan
      iconFile: action-create-icon-blk_24x24
    - id: refreshCache
      iconFile: action-refresh-icon-blk_24x24
    - id: purgeCompletedDeploymentProgressObjects
      iconFile: delete-icon-blk_24x24
