# Copyright 2020, 2022, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

perspectives:
  - id: configuration
    type: built-in
    iconFiles:
      light: navstrip-icon-readwrite-configuration-blk_48x48
      dark: navstrip-icon-readwrite-configuration-wht_48x48
      greyed: navstrip-icon-readwrite-configuration-gry_48x48
    beanTree: edit
  - id: monitoring
    type: built-in
    iconFiles:
      light: navstrip-icon-monitoring-blk_48x48
      dark: navstrip-icon-monitoring-wht_48x48
      greyed: navstrip-icon-monitoring-gry_48x48
    beanTree: domainRuntime
  - id: view
    type: built-in
    iconFiles:
      light: navstrip-icon-readonly-configuration-blk_48x48
      dark: navstrip-icon-readonly-configuration-wht_48x48
      greyed: navstrip-icon-readonly-configuration-gry_48x48
    beanTree: serverConfig
  - id: security
    type: built-in
    iconFiles:
      light: navstrip-icon-security-blk_48x48
      dark: navstrip-icon-security-wht_48x48
      greyed: navstrip-icon-security-gry_48x48
    beanTree: securityData
  - id: modeling
    type: built-in
    iconFiles:
      light: navstrip-icon-wdt-blk_48x48
      dark: navstrip-icon-wdt-wht_48x48
      greyed: navstrip-icon-wdt-gry_48x48
    beanTree: model
  - id: composite
    type: built-in
    iconFiles:
      light: navstrip-icon-wdt-composite-blk_48x48
      dark: navstrip-icon-wdt-composite-wht_48x48
      greyed: navstrip-icon-wdt-composite-gry_48x48
    beanTree: compositeConfig
  - id: properties
    type: built-in
    iconFiles:
      light: navstrip-icon-property-list-blk_48x48
      dark: navstrip-icon-property-list-wht_48x48
      greyed: navstrip-icon-property-list-gry_48x48
    beanTree: propertyList
  - id: ancillary
    type: add-in
    iconFiles:
      light: navstrip-icon-nodata-blk_48x48
      dark: navstrip-icon-nodata-blk_48x48
      greyed: navstrip-icon-empty_48x48
    beanTree: project
