'use strict';

require('./tests/basic_test.js');
require('./tests/navtree1_test.js');
require('./tests/navtree2_test.js');
require('./tests/navtree3_test.js');
require('./tests/navtree4_test.js');
require('./tests/navtree5_test.js');
require('./tests/configPanel_test.js');
require('./tests/domainProps_test.js');
require('./tests/serverAndTemplate_test.js');
require('./tests/machineAndCluster_test.js');
require('./tests/monitoring_test.js');
require('./tests/monitoringPanel_test.js');
require('./tests/utilities_test');
require('./tests/services_test');
require('./tests/security_test');
require('./tests/interop_test');
require('./tests/deploy_test');
require('./tests/scheduling_test');
require('./tests/wdt_test');
require('./tests/helpLink_test');
require('./tests/nonAdminUser_test');
require('./tests/ucdAsProvider_test');
