# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.descriptor.SettableBean
descriptionHTML: ' '
name: weblogic.coherence.app.descriptor.wl.ApplicationLifecycleListenerBean
properties:
- defaultValue: {
    }
  descriptionHTML: '<p> The class that implements ApplicationLifecycleEventListener.
    </p> '
  name: ClassName
  nullable: true
  redeployNeeded: true
  restartNeeded: true
  type: java.lang.String
  writable: true
- defaultValue: {
    }
  descriptionHTML: '<p> The init params for the ApplicationLifecycleEventListener
    class </p> '
  name: InitParams
  relationship: containment
  type: weblogic.coherence.app.descriptor.wl.InitParamsBean
roles:
  allowed:
  - Deployer
