# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.configuration.ConfigurationMBean
descriptionHTML: '<p>Encapsulates information about a property, such as its value
  and whether it is encrypted.</p> '
name: weblogic.management.configuration.ConfigurationPropertyMBean
properties:
- defaultValue:
    value:
      value: false
  descriptionHTML: '<p>Specifies whether the property should be encrypted.</p>  <p>
    By default, the value of a property is not encrypted and anyone using the Administration
    Console can view the value of the property. If this attribute is set to true,
    then the value of the property on the Administration Console will be set to all
    asterisks.</p> '
  name: EncryptValueRequired
  type: boolean
  writable: true
- defaultValue:
    value:
      value: ''
  descriptionHTML: '<p>Specifies the decrypted value of the property.</p>  <p>Note:
    In release 10.3.1 of WebLogic Server, the behavior of the MBean encryption algorithm
    changed. In previous releases, if the newly set value was identical to the existing
    value, the encrypted value did not change.  That is, you would always get the
    same encrypted value for a given password   The action was not treated as a (non-dynamic)
    change. The behavior has been modified so that use of the setter on any existing
    encrypted value is considered to be a (dynamic) change, regardless of whether
    the new value matches the old value. Therefore, even if you set the password to
    the existing value, the setter now generates a different encrypted value for the
    given password.</p>  <p>Use this attribute if you have specified that property
    should be encrypted.</p> '
  encrypted: true
  name: EncryptedValue
  type: java.lang.String
  writable: true
- array: true
  defaultValue: {
    }
  descriptionHTML: '<p>Get the encrytped bytes from EncryptedValue attribute</p> '
  encrypted: true
  name: EncryptedValueEncrypted
  type: byte
- defaultValue:
    value:
      value: ''
  descriptionHTML: '<p>Specifies the value of the property.</p>  <p>If the property
    is encrypted, then attribute is null and one should use the EncryptedValue attribute
    to get the decrypted value.</p> '
  name: Value
  type: java.lang.String
  writable: true
