# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.configuration.PartitionConfiguratorMBean
descriptionHTML: 'The create-cluster-target-provider configuration in a partition
  template. '
name: weblogic.management.configuration.LeastOccupiedPartitionConfiguratorMBean
