# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

baseTypes:
- weblogic.management.configuration.ConfigurationMBean
descriptionHTML: 'A partition configurator defined in a partition template. A configuration
  may define zero or more providers. '
name: weblogic.management.configuration.PartitionConfiguratorMBean
